# Generated by Django 5.0.3 on 2024-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('place', models.TextField()),
                ('phone', models.IntegerField()),
                ('whatsapp', models.TextField()),
            ],
        ),
    ]
