# Generated by Django 5.1.2 on 2024-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('img', models.FileField(upload_to='')),
                ('dim', models.TextField()),
                ('duration', models.TextField()),
                ('certi', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
